# Generated by Django 5.2.4 on 2025-07-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(choices=[('Greater Portmore', 'Greater Portmore'), ('Old Harbour', 'Old Harbour'), ('St. Jago Park', 'St. Jago Park'), ('Linstead', 'Linstead')], max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('priority_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Low', max_length=255)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Verified', 'Verified'), ('Assigned', 'Assigned'), ('Closed', 'Closed')], default='Open', max_length=255)),
                ('assigned_to', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField()),
            ],
        ),
    ]
