# Generated by Django 5.2.4 on 2025-07-31 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='report',
            name='closed_at',
        ),
        migrations.RemoveField(
            model_name='report',
            name='department',
        ),
        migrations.RemoveField(
            model_name='report',
            name='name',
        ),
        migrations.AddField(
            model_name='report',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='report',
            name='issue_type',
            field=models.CharField(choices=[('Select', 'Select'), ('Carpentry', 'Carpentry'), ('Electrical', 'Electrical'), ('Masonry', 'Masonry'), ('Plumbing', 'Plumbing'), ('Air Conditioning', 'Air Conditioning'), ('Other', 'Other')], default='Select', max_length=255),
        ),
        migrations.AddField(
            model_name='report',
            name='reporter',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='reported_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='resolution_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='location',
            field=models.CharField(choices=[('Select', 'Select'), ('Greater Portmore', 'Greater Portmore'), ('Old Harbour', 'Old Harbour'), ('St. Jago Park', 'St. Jago Park'), ('Linstead', 'Linstead')], default='Select', max_length=255),
        ),
        migrations.AlterField(
            model_name='report',
            name='priority_level',
            field=models.CharField(choices=[('Select', 'Select'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Select', max_length=255),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('Select', 'Select'), ('Open', 'Open'), ('Verified', 'Verified'), ('Assigned', 'Assigned'), ('Closed', 'Closed')], default='Select', max_length=255),
        ),
    ]
