# Generated by Django 5.2.4 on 2025-08-03 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alter_report_options_remove_report_closed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='location',
            field=models.CharField(choices=[('Select', 'Select'), ('Spanish Town', 'Spanish Town'), ('Greater Portmore', 'Greater Portmore'), ('Old Harbour', 'Old Harbour'), ('St. Jago Park', 'St. Jago Park'), ('Linstead', 'Linstead')], default='Select', max_length=255),
        ),
    ]
