# Generated by Django 5.2.4 on 2025-08-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_alter_report_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='department',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='report',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name="Reporter's Email"),
        ),
        migrations.AddField(
            model_name='report',
            name='full_name',
            field=models.CharField(default='', max_length=100, verbose_name="Reporter's Full Name"),
        ),
        migrations.AddField(
            model_name='report',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Contact Phone'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Verified', 'Verified'), ('Assigned', 'Assigned'), ('Closed', 'Closed')], default='Open', max_length=255),
        ),
    ]
